# Site settings
name: Faraday's Softcode
title: Code for PennMUSH
email: faraday@aresmush.com
description: "Utilities designed for PennMUSH online text-based game servers."
copyright: "Copyright 2014 by Linda Naughton"
baseurl: ""
siteroot: "/MUSH"
url: "http://www.aresmush.com"
username: lynnfaraday
category-list: [ install, addons, core, fs3 ]

# Build settings
markdown: kramdown
permalinks: pretty
