# -----------------------------------------------------------------------------
# -- AresMUSH.  Copyright 2010 by Linda Naughton ("Faraday")
# -- See http://www.wordsmyth.org/aresmush for documentation and license info.
# -----------------------------------------------------------------------------
# DESCRIPTION:
# The main dispatcher for system events, including events generated by other
# modules and (most often) commands generated by players.  Events are dumped
# into a queue and sent to the modules one by one.
# -----------------------------------------------------------------------------

import sys
import logging
import traceback

from aresmush.modules.management import moduleManager
from aresmush.engine.commands import command

# TODO: Should probably rename this just to 'dispatcher' since there'll be other events later.
class CommandDispatcher:
    
    def __init__(self):
        logging.info("Creating command dispatcher.")

    # TODO: Ultimately this will need to dump into a thread-safe queue and have
    # a separate loop for dispatching
    def processCommand(self, connection, commandString):
        # TODO: Don't log connect or password commands.
        logging.debug("Got command %s from %s" % (commandString, str(connection.client_address)))
        cmd = command.Command(commandString)
        cmd.connection = connection
        self.dispatchEvent(cmd)
    
    # TODO: This needs to get smarter about event dispatching and handling special cases like the "anyHandled"
    def dispatchEvent(self, event):
        try:
            anyHandled = False
                        
            for key, module in moduleManager.rootModuleManager.modules.iteritems():
				# Call either the anon command or regular version depending on whether the
				# person is logged in.
                if (event.connection.player == None):
                    handled = module.currentInstance.handleAnonCommand(event)
                else:
                    handled = module.currentInstance.handleCommand(event)
                anyHandled = anyHandled or handled
            
            if (anyHandled == False):
                event.connection.send("%s %s" % ( event.connection._("<GAME>"), 
                     event.connection._("I don't recognize that command.") ))
        except SystemExit:
           logging.info("Got system exit request.  Goodbye!")
           raise
        
        except BaseException as detail:
            traceback.print_exc
            logging.error("Ooops!  Something went awry with your event: %s" % detail)
       
  